pipeline:
  build:
    image: cp2017/xvfb
    commands:
      - npm install typescript
      - npm install enhanced-resolve
      - npm install
      - ./test.sh
  slack:
    image: plugins/slack
    channel: drone
    username: drone

services:
  ipfs:
   image: qnib/cp2017-ipfs
   container_name: ipfs
  geth:
   image: cp2017/geth
   container_name: geth


#  publish:
#    image: plugins/coverage
#    server: http://ec2-54-194-144-141.eu-west-1.compute.amazonaws.com:8080
#    token: $$GITHUB_API_KEY
#    includes: coverage/coverage.lcov

