pipeline:
  build:
    image: cp2017/xvfb
    commands:
      - npm install typescript
      - npm install enhanced-resolve
      - npm install 
      - ./test.sh

services:
  ipfs:
   image: qnib/cp2017-ipfs
   container_name: ipfs
   volumes:
    - /data/ipfs
    - /export
  geth:
   image: qnib/cp2017-geth
   container_name: geth

publish:
  coverage:
    server: http://ec2-54-194-144-141.eu-west-1.compute.amazonaws.com:8080
    token: $$GITHUB_API_KEY
    includes: coverage/coverage.lcov

notify:
  slack:
    webhook_url: https://hooks.slack.com/services/$$SLACK_TOKEN
    channel: drone
    username: drone
    template: >
      {{ repo.full_name }} ({{ repo.repo_link }}) finished build #{{ build.number }} with status {{ build.status }}
    when:
      branch: master
