build:
  image: node:$$NODE_VERSION
  commands:
    - npm install -g angular-cli
    - npm install
    - npm install enhanced-resolve

#publish:
#  docker:
#    username: $$DOCKER_USER
#    password: $$DOCKER_PASSWORD
#    email: $$DOCKER_EMAIL
#    repo: cp2017/webapp
#    tag: latest
#    file: Dockerfile
#    insecure: false

notify:
  slack:
    webhook_url: https://hooks.slack.com/services/$$SLACK_TOKEN
    channel: drone
    username: drone
    template: >
      {{ repo.full_name }} ({{ repo.repo_link }}) finished build #{{ build.number }} with status {{ build.status }}
    when:
      branch: master

matrix:
  NODE_VERSION:
   - 7.2.1
