pipeline:
  check:
    image: cp2017/geth:2017-01-13.1
    commands:
      - sleep 5
      - geth --exec 'eth.accounts' attach http://localhost:8545
  build:
    image: cp2017/xvfb
    commands:
      - sleep 5
      - npm install typescript
      - npm install enhanced-resolve
      - npm install
      - ./test.sh
  slack:
    image: plugins/slack
    channel: drone
    username: drone

services:
  ipfs:
   image: qnib/cp2017-ipfs
   container_name: ipfs
   pull: true
  geth:
   image: cp2017/geth:2017-01-13.1
   pull: true
   container_name: geth
   environment:
    - GETH_TEST_DATABASE=false
    - GETH_BOOTSTRAP=true


#  publish:
#    image: plugins/coverage
#    server: http://ec2-54-194-144-141.eu-west-1.compute.amazonaws.com:8080
#    token: $$GITHUB_API_KEY
#    includes: coverage/coverage.lcov

